# Meta Data for SEO

## Homepage
title = "StructML"
titleSeparator = "-"
titleAddition = "ML Platform "
description = "a ML platform that helps you in going quickly from unstructured to structured data"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "structml.com"
titleHome = "StructML"

## Twitter Cards
twitterSite = "@structml"
twitterCreator = "@structml"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/structml"
schemaAuthorGitHub = "https://github.com/structml"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/structml"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/structml"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Built with ❤️ by StructML Team"

# Feed
copyRight = "Copyright (c) 2023- Krishna"

# Alert
alert = false
alertText = "Like StructML? <a class=\"alert-link\" href=\"https://github.com/structml\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/structml"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false
